
###############################



PART 3


Each Pokemon primary type

mysql> select name, primary_type from pokemons;
+-------------+--------------+
| name        | primary_type |
+-------------+--------------+
| Smeargle    |            1 |
| Wailord     |            2 |
| Vileplume   |            3 |
| Armaldo     |            4 |
| Cradily     |            4 |
| Carvanha    |            2 |
| Numel       |            5 |
| Sandslash   |            6 |
| Ninetales   |            5 |
| Weepinbell  |            3 |
| Gloom       |            3 |
| Ivysaur     |            3 |
| Nidorino    |            7 |
| Nidoking    |            7 |
| Dugtrio     |            6 |
| Rhyhorn     |            6 |
| Persian     |            1 |
| Wartortle   |            2 |
| Charmeleon  |            5 |
| Charizard   |            5 |
| Exeggutor   |            3 |
| Cloyster    |            2 |
| Arcanine    |            5 |
| Parasect    |            8 |
| Dewgong     |            2 |
| Chansey     |            1 |
| Kingler     |            2 |
| Tentacruel  |            2 |
| Blastoise   |            2 |
| Bellsprout  |            3 |
| Victreebel  |            3 |
| Rapidash    |            5 |
| Magneton    |            9 |
| Quagsire    |            2 |
| Exeggcute   |            3 |
| Horsea      |            2 |
| Electrode   |            9 |
| Starmie     |            2 |
| Seadra      |            2 |
| Butterfree  |            8 |
| Bellossom   |            3 |
| Dragonair   |           10 |
| Poliwhirl   |            2 |
| Flareon     |            5 |
| Eevee       |            1 |
| Vaporeon    |            2 |
| Jolteon     |            9 |
| Goldeen     |            2 |
| Seaking     |            2 |
| Golduck     |            2 |
| Staryu      |            2 |
| Pikachu     |            9 |
| Shellder    |            2 |
| Marill      |            2 |
| Skiploom    |            3 |
| Dratini     |           10 |
| Bulbasaur   |            3 |
| Venusaur    |            3 |
| Charmander  |            5 |
| Squirtle    |            2 |
| Nidoqueen   |            7 |
| Pidgeot     |            1 |
| Electabuzz  |            9 |
| Tangela     |            3 |
| Tauros      |            1 |
| Manectric   |            9 |
| Muk         |            7 |
| Azumarill   |            2 |
| Zangoose    |            1 |
| Wingull     |            2 |
| Roselia     |            3 |
| Pelipper    |            2 |
| Camerupt    |            5 |
| Mawile      |           11 |
| Sableye     |           12 |
| Swellow     |            1 |
| Trapinch    |            6 |
| Wailmer     |            2 |
| Shiftry     |            3 |
| Cacturne    |            3 |
| Lairon      |           11 |
| Linoone     |            1 |
| Milotic     |            2 |
| Delcatty    |            1 |
| Nosepass    |            4 |
| Medicham    |           13 |
| Ludicolo    |            2 |
| Kecleon     |            1 |
| Graveler    |            4 |
| Loudred     |            1 |
| Dodrio      |            1 |
| Kadabra     |           14 |
| Claydol     |            6 |
| Sharpedo    |            2 |
| Magcargo    |            5 |
| Electrike   |            9 |
| Makuhita    |           13 |
| Hariyama    |           13 |
| Wigglytuff  |            1 |
| Vigoroth    |            1 |
| Skarmory    |           11 |
| Spinda      |            1 |
| Exploud     |            1 |
| Slaking     |            1 |
| Lanturn     |            2 |
| Slakoth     |            1 |
| Absol       |           12 |
| Tropius     |            3 |
| Gardevoir   |           14 |
| Torkoal     |            5 |
| Lunatone    |            4 |
| Solrock     |            4 |
| Dusclops    |           15 |
| Tyranitar   |            4 |
| Clefairy    |           16 |
| Jigglypuff  |            1 |
| Kingdra     |            2 |
| Paras       |            8 |
| Lapras      |            2 |
| Rhydon      |            6 |
| Slowbro     |            2 |
| Ursaring    |            1 |
| Machoke     |           13 |
| Kangaskhan  |            1 |
| Machamp     |           13 |
| Oddish      |            3 |
| Girafarig   |            1 |
| Ponyta      |            5 |
| Vulpix      |            5 |
| Raticate    |            1 |
| Marowak     |            6 |
| Nidorina    |            7 |
| Onix        |            4 |
| Aerodactyl  |            4 |
| Sneasel     |           12 |
| Gastly      |           15 |
| Haunter     |           15 |
| Gengar      |           15 |
| Grotle      |            3 |
| Snover      |            3 |
| Ambipom     |            1 |
| Raichu      |            9 |
| Gastrodon   |            2 |
| Pachirisu   |            9 |
| Blissey     |            1 |
| Sudowoodo   |            4 |
| Misdreavus  |           15 |
| Drifblim    |           15 |
| Skorupi     |            7 |
| Steelix     |           11 |
| Lopunny     |            1 |
| Hippopotas  |            6 |
| Mightyena   |           12 |
| Kirlia      |           14 |
| Flaaffy     |            9 |
| Ampharos    |            9 |
| Monferno    |            5 |
| Gyarados    |            2 |
| Luxio       |            9 |
| Mothim      |            8 |
| Salamence   |           10 |
| Honchkrow   |           12 |
| Staravia    |            1 |
| Metagross   |           11 |
| Drapion     |            7 |
| Floatzel    |            2 |
| Stantler    |            1 |
| Carnivine   |            3 |
| Primeape    |           13 |
| Glameow     |            1 |
| Purugly     |            1 |
| Alakazam    |           14 |
| Yanma       |            8 |
| Bibarel     |            1 |
| Beautifly   |            8 |
| Meowth      |            1 |
| Hypno       |           14 |
| Dunsparce   |            1 |
| Scyther     |            8 |
| Rampardos   |            4 |
| Pinsir      |            8 |
| Lickitung   |            1 |
| Miltank     |            1 |
| Granbull    |           16 |
| Cherrim     |            3 |
| Larvitar    |            4 |
| Clefable    |           16 |
| Torterra    |            3 |
| Glalie      |           17 |
| Crobat      |            7 |
| Aipom       |            1 |
| Beedrill    |            8 |
| Porygon2    |            1 |
| Bronzor     |           11 |
| Snorunt     |           17 |
| Scizor      |            8 |
| Swalot      |            7 |
| Magnezone   |            9 |
| Magmar      |            5 |
| Electivire  |            9 |
| Magmortar   |            5 |
| Gligar      |            6 |
| Buizel      |            2 |
| Gliscor     |            6 |
| Probopass   |            4 |
| Tyrogue     |           13 |
| Hitmonchan  |           13 |
| Piloswine   |           17 |
| Staraptor   |            1 |
| Jumpluff    |            3 |
| Banette     |           15 |
| Ralts       |           14 |
| Roserade    |            3 |
| Lickilicky  |            1 |
| Abomasnow   |            3 |
| Metang      |           11 |
| Seviper     |            7 |
| Luxray      |            9 |
| Buneary     |            1 |
| Mamoswine   |           17 |
| Vibrava     |            6 |
| Flygon      |            6 |
| Nuzleaf     |            3 |
| Pupitar     |            4 |
| Magnemite   |            9 |
| Mareep      |            9 |
| Growlithe   |            5 |
| Slowking    |            2 |
| Drilbur     |            6 |
| Zebstrika   |            9 |
| Swoobat     |           14 |
| Stoutland   |            1 |
| Furret      |            1 |
| Gabite      |           10 |
| Grumpig     |           14 |
| Vanillish   |           17 |
| Gothorita   |           14 |
| Duosion     |           14 |
| Simisage    |            3 |
| Simisear    |            5 |
| Simipour    |            2 |
| Galvantula  |            8 |
| Sawsbuck    |            1 |
| Jellicent   |            2 |
| Fraxure     |           10 |
| Whimsicott  |            3 |
| Tirtouga    |            2 |
| Deino       |           12 |
| Druddigon   |           10 |
| Klang       |           11 |
| Seismitoad  |            2 |
| Scolipede   |            8 |
| Mienfoo     |           13 |
| Elgyem      |           14 |
| Pawniard    |           12 |
| Liepard     |           12 |
| Watchog     |            1 |
| Alomomola   |            2 |
| Klinklang   |           11 |
| Beheeyem    |           14 |
| Cubchoo     |           17 |
| Leavanny    |            8 |
| Archen      |            4 |
| Eelektrik   |            9 |
| Accelgor    |            8 |
| Espeon      |           14 |
| Walrein     |           17 |
| Gallade     |           14 |
| Jynx        |           17 |
| Rotom       |            9 |
| Gothita     |           14 |
| Lilligant   |            3 |
| Ducklett    |            2 |
| Krokorok    |            6 |
| Palpitoad   |            2 |
| Lampent     |           15 |
| Unfezant    |            1 |
| Axew        |           10 |
| Golurk      |            6 |
| Sigilyph    |           14 |
| Tangrowth   |            3 |
| Heatmor     |            5 |
| Umbreon     |           12 |
| Mismagius   |           15 |
| Klink       |           11 |
| Mantine     |            2 |
| Basculin    |            2 |
| Emolga      |            9 |
| Herdier     |            1 |
| Excadrill   |            6 |
| Swanna      |            2 |
| Mandibuzz   |           12 |
| Toxicroak   |            7 |
| Braviary    |            1 |
| Cofagrigus  |           15 |
| Beartic     |           17 |
| Durant      |            8 |
| Ferroseed   |            3 |
| Ferrothorn  |            3 |
| Lucario     |           13 |
| Weavile     |           12 |
| Weezing     |            7 |
| Bronzong    |           11 |
| Eelektross  |            9 |
| Doublade    |           11 |
| Chandelure  |           15 |
| Crustle     |            8 |
| Doduo       |            1 |
| Helioptile  |            9 |
| Carbink     |            4 |
| Cryogonal   |           17 |
| Vanilluxe   |           17 |
| Delibird    |           17 |
| Rhyperior   |            6 |
| Masquerain  |            8 |
| Golem       |            4 |
| Froslass    |           17 |
| Shedinja    |            8 |
| Breloom     |            3 |
| Bagon       |           10 |
| Talonflame  |            5 |
| Haxorus     |           10 |
| Slugma      |            5 |
| Goomy       |           10 |
| Sylveon     |           16 |
| Grimer      |            7 |
| Goodra      |           10 |
| Fearow      |            1 |
| Garbodor    |            7 |
| Slowpoke    |            2 |
| Sandshrew   |            6 |
| Psyduck     |            2 |
| Poliwag     |            2 |
| Diglett     |            6 |
| Seel        |            2 |
| Voltorb     |            9 |
| Ditto       |            1 |
| Koffing     |            7 |
| Moltres     |            5 |
| Kabutops    |            4 |
| Dragonite   |           10 |
| Snorlax     |            1 |
| Omastar     |            4 |
| Poliwrath   |            2 |
| Mew         |           14 |
| Zapdos      |            9 |
| Remoraid    |            2 |
| Politoed    |            2 |
| Venonat     |            8 |
| Celebi      |           14 |
| Raikou      |            9 |
| Chikorita   |            3 |
| Totodile    |            2 |
| Cyndaquil   |            5 |
| Bayleef     |            3 |
| Croconaw    |            2 |
| Quilava     |            5 |
| Anorith     |            4 |
| Sunkern     |            3 |
| Hoppip      |            3 |
| Luvdisc     |            2 |
| Hoothoot    |            1 |
| Treecko     |            3 |
| Sunflora    |            3 |
| Taillow     |            1 |
| Togepi      |           16 |
| Surskit     |            8 |
| Blaziken    |            5 |
| Sceptile    |            3 |
| Swampert    |            2 |
| Altaria     |           10 |
| Mudkip      |            2 |
| Zubat       |            7 |
| Cacnea      |            3 |
| Barboach    |            2 |
| Seedot      |            3 |
| Typhlosion  |            5 |
| Feraligatr  |            2 |
| Meganium    |            3 |
| Jirachi     |           11 |
| Xatu        |           14 |
| Latias      |           10 |
| Illumise    |            8 |
| Entei       |            5 |
| Gorebyss    |            2 |
| Suicune     |            2 |
| Aggron      |           11 |
| Donphan     |            6 |
| Golbat      |            7 |
| Noctowl     |            1 |
| Forretress  |            8 |
| Houndoom    |           12 |
| Castform    |            1 |
| Rayquaza    |           10 |
| Huntail     |            2 |
| Volbeat     |            8 |
| Dustox      |            8 |
| Ledian      |            8 |
| Ariados     |            8 |
| Relicanth   |            2 |
| Octillery   |            2 |
| Lombre      |            2 |
| Clamperl    |            2 |
| Teddiursa   |            1 |
| Nincada     |            8 |
| Swinub      |           17 |
| Sentret     |            1 |
| Pineco      |            8 |
| Skitty      |            1 |
| Zigzagoon   |            1 |
| Heracross   |            8 |
| Wobbuffet   |           14 |
| Regice      |           17 |
| Swablu      |            1 |
| Plusle      |            9 |
| Minun       |            9 |
| Spoink      |           14 |
| Qwilfish    |            2 |
| Combusken   |            5 |
| Azurill     |            1 |
| Igglybuff   |            1 |
| Togetic     |           16 |
| Corsola     |            2 |
| Baltoy      |            6 |
| Articuno    |           17 |
| Lileep      |            4 |
| Chimecho    |           14 |
| Murkrow     |           12 |
| Sealeo      |           17 |
| Ledyba      |            8 |
| Sliggoo     |           10 |
| Lumineon    |            2 |
| Shelgon     |           10 |
| Poochyena   |           12 |
| Corphish    |            2 |
| Phanpy      |            6 |
| Whismur     |            1 |
| Regirock    |            4 |
| Registeel   |           11 |
| Groudon     |            6 |
| Shuckle     |            8 |
| Hitmontop   |           13 |
| Geodude     |            4 |
| Grovyle     |            3 |
| Marshtomp   |            2 |
| Beldum      |           11 |
| Wynaut      |           14 |
| Lotad       |            2 |
| Machop      |           13 |
| Shroomish   |            3 |
| Turtwig     |            3 |
| Budew       |            3 |
| Combee      |            8 |
| Cherubi     |            3 |
| Gogoat      |            3 |
| Bonsly      |            4 |
| Kricketune  |            8 |
| Abra        |           14 |
| Ninjask     |            8 |
| Wooper      |            2 |
| Latios      |           10 |
| Natu        |           14 |
| Spheal      |           17 |
| Whiscash    |            2 |
| Shuppet     |           15 |
| Meditite    |           13 |
| Cascoon     |            8 |
| Feebas      |            2 |
| Chinchou    |            2 |
| Aron        |           11 |
| Torchic     |            5 |
| Fletchinder |            5 |
| Bisharp     |           12 |
| Pansear     |            5 |
| Panpour     |            2 |
| Sawk        |           13 |
| Throh       |           13 |
| Darumaka    |            5 |
| Bouffalant  |            1 |
| Boldore     |            4 |
| Gigalith    |            4 |
| Minccino    |            1 |
| Scraggy     |           12 |
| Cottonee    |            3 |
| Maractus    |            3 |
| Porygon-Z   |            1 |
| Pidove      |            1 |
| Petilil     |            3 |
| Tranquill   |            1 |
| Munna       |           14 |
| Swadloon    |            8 |
| Dwebble     |            8 |
| Croagunk    |            7 |
| Blitzle     |            9 |
| Sandile     |            6 |
| Cubone      |            6 |
| Omanyte     |            4 |
| Shieldon    |            4 |
| Archeops    |            4 |
| Mantyke     |            2 |
| Vanillite   |           17 |
| Woobat      |           14 |
| Riolu       |           13 |
| Timburr     |           13 |
| Kabuto      |            4 |
| Cranidos    |            4 |
| Carracosta  |            2 |
| Fletchling  |            1 |
| Bunnelby    |            1 |
| Pansage     |            3 |
| Tentacool   |            2 |
| Snubbull    |           16 |
| Houndour    |           12 |
| Clauncher   |            2 |
| Scatterbug  |            8 |
| Burmy       |            8 |
| Bidoof      |            1 |
| Dragalge    |            7 |
| Klefki      |           11 |
| Cobalion    |           11 |
| Terrakion   |            4 |
| Virizion    |            3 |
| Scrafty     |           12 |
| Gurdurr     |           13 |
| Mienshao    |           13 |
| Hitmonlee   |           13 |
| Conkeldurr  |           13 |
| Hawlucha    |           13 |
| Rattata     |            1 |
| Pidgeotto   |            1 |
| Finneon     |            2 |
| Elekid      |            9 |
| Espurr      |           14 |
| Krookodile  |            6 |
| Krabby      |            2 |
| Pidgey      |            1 |
| Wurmple     |            8 |
| Crawdaunt   |            2 |
| Stunky      |            7 |
| Drifloon    |           15 |
| Magby       |            5 |
| Gulpin      |            7 |
| Arbok       |            7 |
| Joltik      |            8 |
| Ekans       |            7 |
| Mankey      |           13 |
| Venomoth    |            8 |
| Spearow     |            1 |
| Starly      |            1 |
| Infernape   |            5 |
| Roggenrola  |            4 |
| Pangoro     |           13 |
| Smoochum    |           17 |
| Kyogre      |            2 |
| Silcoon     |            8 |
| Mewtwo      |           14 |
| Golett      |            6 |
| Garchomp    |           10 |
| Volcarona   |            8 |
| Audino      |            1 |
| Togekiss    |           16 |
| Dusknoir    |           15 |
| Hydreigon   |           12 |
| Heatran     |            5 |
| Cresselia   |           14 |
| Musharna    |           14 |
| Weedle      |            8 |
| Caterpie    |            8 |
| Kakuna      |            8 |
| Metapod     |            8 |
| Kricketot   |            8 |
| Magikarp    |            2 |
| Spinarak    |            8 |
| Vespiquen   |            8 |
| Drowzee     |           14 |
| Shinx       |            9 |
| Chimchar    |            5 |
| Skuntank    |            7 |
| Sewaddle    |            8 |
| Cleffa      |           16 |
| Pichu       |            9 |
| Duskull     |           15 |
| Unown       |           14 |
| Munchlax    |            1 |
| Porygon     |            1 |
| Gible       |           10 |
| Prinplup    |            2 |
| Whirlipede  |            8 |
| Noivern     |           18 |
| Pyroar      |            5 |
| Florges     |           16 |
| Clawitzer   |            2 |
| Barbaracle  |            4 |
| Dedenne     |            9 |
| Floette     |           16 |
| Slurpuff    |           16 |
| Aromatisse  |           16 |
| Shellos     |            2 |
| Stunfisk    |            6 |
| Frillish    |            2 |
| Hippowdon   |            6 |
| Chatot      |            1 |
| Lillipup    |            1 |
| Venipede    |            8 |
| Bastiodon   |            4 |
| Tynamo      |            9 |
| Diggersby   |            1 |
| Chingling   |           14 |
| Trubbish    |            7 |
| Cinccino    |            1 |
| Glaceon     |           17 |
| Leafeon     |            3 |
| Regigigas   |            1 |
| Purrloin    |           12 |
| Nidoran     |            7 |
| Deerling    |            1 |
| Shelmet     |            8 |
| Patrat      |            1 |
| Escavalier  |            8 |
| Avalugg     |           17 |
| Vivillon    |            8 |
| Heliolisk   |            9 |
| Aurorus     |            4 |
| Tyrantrum   |            4 |
| Yanmega     |            8 |
| Spiritomb   |           15 |
| Vullaby     |           12 |
| Zoroark     |           12 |
| Amoonguss   |            3 |
| Tympole     |            2 |
| Piplup      |            2 |
| Empoleon    |            2 |
| Furfrou     |            1 |
| Solosis     |           14 |
| Larvesta    |            8 |
| Foongus     |            3 |
| Litwick     |           15 |
| Yamask      |           15 |
| Gothitelle  |           14 |
| Reuniclus   |           14 |
| Pancham     |           13 |
| Litleo      |            5 |
| Skiddo      |            3 |
| Rufflet     |            1 |
| Karrablast  |            8 |
| Lugia       |           14 |
| Binacle     |            4 |
| Skrelp      |            7 |
| Malamar     |           12 |
| Zekrom      |           10 |
| Reshiram    |           10 |
| Happiny     |            1 |
| Zweilous    |           12 |
| Trevenant   |           15 |
| Swirlix     |           16 |
| Spewpa      |            8 |
+-------------+--------------+
656 rows in set (0.00 sec)




##########################




Rufflets secondary type


mysql> select secondary_type from pokemons where name='Rufflet';
+----------------+
| secondary_type |
+----------------+
|             18 |
+----------------+
1 row in set (0.00 sec)




###########################






mysql> select * from pokemon_trainer where trainerID = 303;
+-----------+-----------+------+-------+--------+---------+-------+-------+-------+------------+
| trainerID | pokelevel | hp   | maxhp | attack | defense | spatk | spdef | speed | pokemon_id |
+-----------+-----------+------+-------+--------+---------+-------+-------+-------+------------+
|       303 |        57 |  281 |   281 |    128 |      76 |   128 |    76 |    93 |          2 |
|       303 |        57 |  173 |   173 |    116 |     122 |   150 |   128 |    82 |          3 |
|       303 |        57 |  281 |   281 |    128 |      76 |   128 |    76 |    93 |          2 |
|       303 |        57 |  173 |   173 |    116 |     122 |   150 |   128 |    82 |          3 |
|       303 |        57 |  281 |   281 |    128 |      76 |   128 |    76 |    93 |          2 |
|       303 |        57 |  173 |   173 |    116 |     122 |   150 |   128 |    82 |          3 |
+-----------+-----------+------+-------+--------+---------+-------+-------+-------+------------+
6 rows in set (0.04 sec)



